"""
incept_videos.py  -  the INCEPT_VIDEOS registry: which lessons have an intro VIDEO bound to them.

WHY THIS EXISTS: a Council of Writing Instruction ruled that when a concept lesson has an intro video, the
OPENING written teach_card recap should be COMPRESSED (not kept full, not removed): the video now teaches
the expanded explanation, so the written card keeps only its leading "one idea" callout (which SHOWS the
built target sentence) and drops the trailing expansion. This registry is the single source of truth for
that decision. Its PRESENCE (a lesson id being a key here) is what triggers the teach_card compression in
gated_reading.build_lesson_html per the council rule; ABSENCE means the teach_card renders FULL, exactly
as today.

Parallel to incept_diagrams.INCEPT_DIAGRAMS (diagrams are keyed by (lesson_id, slot); videos are keyed by
lesson_id, since the video is bound to the lesson as a whole, not one slot).

INCEPT_VIDEOS: dict keyed lesson_id:str -> {"mp4": url, "vtt": url}.
  - "mp4": the hosted video url (voiceover video generated by the incept_video stage machinery).
  - "vtt": the captions/subtitles track url.

Ships EMPTY. It is populated later by the wiring step (post-content-lock, after the video stage runs). An
empty registry is a guaranteed no-op: no lesson id matches, so every teach_card renders FULL and the
rendered output is byte-identical to today.
"""

# lesson_id -> {"mp4": url, "vtt": url}. EMPTY until the wiring step binds videos (post-lock).
INCEPT_VIDEOS: dict[str, dict] = {}
